fragment GlobalParts on Global {
  __typename
  navbar {
    __typename
    logoText
    navLinks {
      __typename
      label
      path
    }
  }
  footer {
    __typename
    quote
    description
    instagram
    facebook
  }
}

fragment HomeParts on Home {
  __typename
  hero {
    __typename
    titlePart1
    titlePart2
    subtitle
    video
  }
  founder {
    __typename
    quote
    image
    bio
  }
  philosophy {
    __typename
    hinduismText
    ayurvedaText
    rootSoulText
    branchSymptomText
  }
  individualCare {
    __typename
    title
    description
  }
}

fragment DoctorsParts on Doctors {
  __typename
  name
  lastName
  title
  quote
  tags
  image
  academicBio
  excellence {
    __typename
    title
    description
  }
  expertise {
    __typename
    title
    description
  }
  philosophy
  ui {
    __typename
    consultationButtonLabel
    consultationButtonUrl
    heroBadgeLabel
    heroBadgeText
    journeyHeading
    expertiseHeading
    philosophyBadge
    philosophyHeading
    bridgingHeading
    legacyHeading
    visionHeading
    visionQuote
    ctaLabel
    stats {
      __typename
      value
      label
    }
    philosophyPillars
  }
}

fragment ServicesParts on Services {
  __typename
  header {
    __typename
    tagline
    title
    subtitle
  }
  items {
    __typename
    title
    category
    description
    features
    image
  }
}

fragment ScreeningParts on Screening {
  __typename
  tagline
  title
  subtitle
  pathwayALabel
  pathwayATag
  pathwayBLabel
  pathwayBTag
  pathwayA {
    __typename
    title
    description
    features
  }
  pathwayB {
    __typename
    title
    description
    features
  }
  quiz {
    __typename
    badge
    title
    resetLabel
    incompleteText
    recommendationLabel
    ctaLabel
    ctaPath
    defaultResult {
      __typename
      title
      description
    }
    usaResult {
      __typename
      title
      description
    }
    ancientResult {
      __typename
      title
      description
    }
    questions {
      __typename
      prompt
      a
      b
      aLabel
      bLabel
    }
  }
}

fragment PcpParts on Pcp {
  __typename
  tagline
  title
  subtitle
  features {
    __typename
    title
    description
    icon
  }
}

fragment AestheticsParts on Aesthetics {
  __typename
  tagline
  title
  subtitle
  assessmentLabel
  assessmentHighlights {
    __typename
    title
    description
  }
  synergyCard {
    __typename
    title
    description
    scienceLabel
    scienceTitle
    natureLabel
    natureTitle
  }
  scienceSection {
    __typename
    tagline
    title
    items {
      __typename
      title
      description
    }
  }
  natureSection {
    __typename
    tagline
    title
    items {
      __typename
      title
      description
    }
  }
  packageDeal {
    __typename
    badge
    title
    quote
    bundleLabel
    bundleDescription
    primaryCtaLabel
    primaryCtaPath
    secondaryCtaLabel
    secondaryCtaPath
  }
  services {
    __typename
    title
    description
    image
  }
}

fragment PledgeParts on Pledge {
  __typename
  tagline
  title
  subtitle
  description
  pledges {
    __typename
    physical
    spiritual
    giving
  }
  signBox {
    __typename
    title
    subtitle
    submitLabel
    incompleteAlert
  }
  giftLabels {
    __typename
    physicalTitle
    spiritualTitle
    givingTitle
  }
  successCard {
    __typename
    title
    subtitle
    badge
    officialRegistryLabel
    reviewLabel
  }
  impactCards {
    __typename
    title
    description
    dark
  }
  registryUrl
}

fragment GuidelinesParts on Guidelines {
  __typename
  tagline
  title
  subtitle
}

fragment AppointmentParts on Appointment {
  __typename
  hero {
    __typename
    title
    quote
    clinicalText
    spiritualText
    aestheticText
  }
  contact {
    __typename
    headingHours
    hours
    specialHoursTitle
    specialHours
    locationHeading
    location
    whatsappNumber
  }
  form {
    __typename
    serviceLabel
    timeLabel
    submitLabel
    weekdayOnlyError
    wednesdayOnlyError
  }
  services {
    __typename
    name
    wednesdayOnly
  }
  timeSlots
}

fragment PagesParts on Pages {
  __typename
  title
  blocks {
    __typename
    ... on PagesBlocksHero {
      tagline
      title
      subtitle
    }
    ... on PagesBlocksContentSection {
      title
      body
      image
    }
    ... on PagesBlocksGrid {
      items {
        __typename
        title
        description
        icon
      }
    }
  }
  cta {
    __typename
    title
    description
  }
}
